<?php

/*
 * Icônes Material Symbols demandées à Google Fonts.
 *
 * Fichier généré : ne pas modifier à la main.
 * Régénérer avec `php artisan icons:sync` après avoir ajouté une icône
 * dans une vue, sinon elle s'affichera en toutes lettres.
 */

return [

    'names' => [
        'ac_unit',
        'add',
        'arrow_back',
        'arrow_forward',
        'arrow_upward',
        'auto_awesome',
        'bolt',
        'cake',
        'calendar_today',
        'carpenter',
        'chat',
        'check',
        'check_circle',
        'checkroom',
        'chevron_right',
        'close',
        'computer',
        'content_cut',
        'description',
        'directions_car',
        'diversity_3',
        'download',
        'electric_bolt',
        'expand_more',
        'format_paint',
        'forum',
        'foundation',
        'grid_view',
        'handyman',
        'home',
        'home_repair_service',
        'inbox',
        'info',
        'inventory_2',
        'local_fire_department',
        'local_shipping',
        'location_on',
        'lock',
        'mail',
        'menu',
        'menu_book',
        'music_note',
        'notifications',
        'pause_circle',
        'pending_actions',
        'person',
        'person_search',
        'photo_camera',
        'plumbing',
        'schedule',
        'search',
        'send',
        'shield',
        'shopping_bag',
        'smart_toy',
        'smartphone',
        'spa',
        'star',
        'tune',
        'tv',
        'upload',
        'verified',
        'water_drop',
        'yard',
    ],

];
